pipeline {
    agent any

    tools {
        nodejs 'nodejs'
    }

    stages {

        stage('Workspace Cleaning') {
            steps {
                deleteDir()
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Application-Code') {
                    sh 'npm install'
                }
            }
        }

        stage('Docker Image Build') {
            steps {
                dir('Application-Code') {
                    withDockerRegistry(credentialsId: 'dockerhub-creds', toolName: 'docker') {
                        withCredentials([string(credentialsId: 'tmdb-api', variable: 'TMDB_API_KEY')]) {
                            sh """
                            docker build \
                              --build-arg TMDB_V3_API_KEY=${TMDB_API_KEY} \
                              -t abhishekdocker0118/netflix-clone:latest .
                            """
                        }
                    }
                }
            }
        }

        stage('Docker Image Push') {
            steps {
                withDockerRegistry(credentialsId: 'dockerhub-creds', toolName: 'docker') {
                    sh 'docker push abhishekdocker0118/netflix-clone:latest'
                }
            }
        }

        stage('TRIVY Image Scan') {
            steps {
                sh '''
                docker run --rm \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  aquasec/trivy:latest image \
                  --exit-code 0 \
                  --no-progress \
                  abhishekdocker0118/netflix-clone:latest
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('Kubernetes') {
                    sh 'kubectl apply -f deployment.yml --validate=false'
                    sh 'kubectl apply -f service.yml --validate=false'
                    sh 'kubectl get svc'
                }
            }
        }
    }
}

