pipeline {
    agent any

    tools {
        nodejs 'nodejs'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Application-Code') {
                    sh 'npm install'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Application-Code') {
                    withDockerRegistry(credentialsId: 'dockerhub-creds', url: 'https://index.docker.io/v1/') {
                        withCredentials([string(credentialsId: 'tmdb-api', variable: 'TMDB_API_KEY')]) {
                            sh """
                            docker build \
                              --build-arg TMDB_V3_API_KEY=${TMDB_API_KEY} \
                              -t abhishekdocker0118/netflix-clone:latest .
                            """
                        }
                    }
                }
            }
        }

        stage('Docker Push') {
            steps {
                withDockerRegistry(credentialsId: 'dockerhub-creds', url: 'https://index.docker.io/v1/') {
                    sh 'docker push abhishekdocker0118/netflix-clone:latest'
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh '''
                docker run --rm \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  aquasec/trivy:latest image \
                  --exit-code 0 \
                  --no-progress \
                  abhishekdocker0118/netflix-clone:latest
                '''
            }
        }
    }
}

